from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('orders/', views.orders, name='orders'),
    path('orders/mark-posted/<int:order_id>/', views.mark_posted, name='mark_posted'),
    path('inventory/', views.inventory, name='inventory'),
    path('inventory/edit/<int:item_id>/', views.edit_inventory, name='edit_inventory'),
    path('purchase-orders/', views.purchase_orders, name='purchase_orders'),
    path('purchase-orders/save/', views.save_purchase_order, name='save_purchase_order'),
    path('inventory/sku-info/<str:sku>/', views.sku_info, name='sku_info'),
    path('logout/', views.dashboard_logout, name='dashboard_logout'),
    path('purchase-orders/add/', views.add_purchase_order, name='add_purchase_order'),
    path('ebay/', views.ebay, name='ebay'),
    path('ebay/update/<int:listing_id>/', views.update_ebay, name='update_ebay'),
    path('listings/', views.listings, name='listings'),
    path('listings/stock/', views.listing_stock_update, name='listing_stock'),
    path('listings/price/', views.listing_price_update, name='listing_price'),
    path('makers/', views.makers, name='makers'),
    path('makers/add/', views.add_maker, name='add_maker'),
    path('makers/edit/<int:maker_id>/', views.edit_maker, name='edit_maker'),
    path('listings/description/', views.listing_description_update, name='listing_description'),
    path('inventory/add/', views.add_product, name='add_product'),
    path('inventory/edit-product/', views.edit_product, name='edit_product'),
    path('inventory/csv/', views.inventory_csv, name='inventory_csv'),
    path('inventory/health/', views.inventory_health, name='inventory_health'),
    path('inventory/bulk/', views.inventory_bulk_upload, name='inventory_bulk'),
    path('inventory/delete/<int:item_id>/', views.delete_product, name='delete_product'),
    path('price-table/', views.price_table, name='price_table'),
    path('price-table/add/', views.add_price, name='add_price'),
    path('price-table/delete/<int:price_id>/', views.delete_price, name='delete_price'),
    path('price-table/edit/<int:price_id>/', views.edit_price, name='edit_price'),
    path('orders/report/', views.orders_report, name='orders_report'),
    path('orders/edit/<int:order_id>/', views.edit_order, name='edit_order'),
    path('listings/create/', views.create_listing, name='create_listing'),
    path('orders/import-ebay/', views.import_ebay_orders, name='import_ebay'),
    path('orders/profit-report/', views.profit_report, name='profit_report'),
    path('orders/combined-profit/', views.combined_profit_report, name='combined_profit_report'),
    path('reports/sales-vs-purchase/', views.sales_vs_purchase, name='sales_vs_purchase'),
    path('reports/inventory-valuation/', views.inventory_valuation, name='inventory_valuation'),
    path('reports/reorder-suggestions/', views.reorder_suggestions, name='reorder_suggestions'),
    path('inventory/stock-movement/', views.stock_movement, name='stock_movement'),
    path('makers/performance/', views.maker_performance, name='maker_performance'),
    path('purchase-orders-full/', views.purchase_orders_full, name='purchase_orders_full'),
    path('purchase-orders-full/add/', views.add_purchase_order_full, name='add_purchase_order_full'),
    path('purchase-orders-full/edit/<int:po_id>/', views.edit_purchase_order, name='edit_purchase_order'),
    path('purchase-orders-full/delete/<int:po_id>/', views.delete_purchase_order, name='delete_purchase_order'),
    path('settings/', views.settings, name='settings'),
    path('shipping-rates/', views.shipping_rates, name='shipping_rates'),
    path('shipping-rates/api/', views.shipping_rate_api, name='shipping_rate_api'),
    path('shipping-rates/toggle-free/<int:rate_id>/', views.toggle_free_shipping, name='toggle_free_shipping'),
    path('shipping-rates/toggle-active/<int:rate_id>/', views.toggle_active_shipping, name='toggle_active_shipping'),
    path('shipping-rates/save/', views.save_shipping_rate, name='save_shipping_rate'),
    path('shipping-rates/delete/<int:rate_id>/', views.delete_shipping_rate, name='delete_shipping_rate'),
    path('inventory/maker-products/<str:maker_name>/', views.maker_products),
    path('inventory/push-ebay/', views.push_to_ebay),
    path('inventory/low-stock-po/', views.low_stock_po),
    path('purchase-orders/receive/', views.receive_po),
    path('purchase-orders/email-po/', views.email_po),
    path('makers/ledger/<str:maker_name>/', views.maker_ledger),
    path('orders/thermal-pdf/', views.thermal_label_pdf, name='thermal_label_pdf'),
    path('orders/thermal-png/', views.thermal_label_png, name='thermal_label_png'),
    path('inventory/sync-prices/', views.sync_prices_to_eshop, name='sync_prices'),
    path('inventory/upload-to-eshop/', views.upload_to_eshop, name='upload_to_eshop'),
    path('orders/update-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
]
