# Generated by Django 5.1.3 on 2026-03-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100, unique=True)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                (
                    "standard_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "tracked_price",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["country"],
            },
        ),
    ]
