# Generated by Django 5.1.3 on 2026-03-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingrate",
            name="has_free_postage",
            field=models.BooleanField(
                default=False,
                help_text="Show free standard postage option for this country",
            ),
        ),
    ]
