# Generated by Django 5.1.3 on 2026-02-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_created_order_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
