# Generated by Django 5.2.11 on 2026-02-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='sku',
        ),
    ]
