# Generated by Django 5.1.3 on 2026-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
